version: '3'
services:

  pythontess:
    container_name: pythonTess_container
    build: 
      context: .
      dockerfile: docker/tesseract/Dockerfile
    ports:
      - "5000:5000"
    networks:
      io-network:
          ipv4_address: 172.19.0.2

  python:
    container_name: python_container
    build: 
      context: .
      dockerfile: docker/python/Dockerfile
    environment:
      DISPLAY: host.docker.internal:0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    networks:
      - io-network
    depends_on:
      - pythontess
      - db


  db:
    container_name: pg_container_io
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: io
    ports:
      - "5432:5432"
    networks:
        io-network:
          ipv4_address: 172.19.0.3

  
  pgadmin:
    container_name: pgadmin4_container_io
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
       io-network:
          ipv4_address: 172.19.0.4

      
networks:
  io-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.19.0.0/16

